pipeline {
	agent any
	
	stages {
		stage('Check stage') {
			steps {
				withMaven(maven : Mvn) {
					sh 'mvn --version'
				}
			}
		}
		
		stage('Compile stage') {
			steps {
				withMaven(maven : Mvn) {
					sh 'mvn clean compile'
				}
			}
		}
		
		stage('Test stage') {
			steps {
				withMaven(maven : Mvn) {
					sh 'mvn test'
				}
			}
		}
	}	
}
