pipeline {
	agent any
	
	stages {
		stage('Check stage') {
			steps {
				withMaven(maven : 'Mvn') {
					sh 'mvn --version'
				}
			}
		}
		
		stage('Compile stage') {
			steps {
				withMaven(maven : 'Mvn') {
					sh 'mvn -f mvn-math/pom.xml compile'
				}
			}
		}
		
		stage('Test stage') {
			steps {
				withMaven(maven : 'Mvn') {
					sh 'mvn -f mvn-math/pom.xml install'
				}
			}
		}
	}	
}
